### ISSUE TITLE
Negative GMT offsets need to be escaped in Bash

### ISSUE THREAD

**Issue by shiftycow** [bluegreen-labs/phenocam_installation_tool_v2#2]
Negative GMT offsets need to be escaped. This should either be documented in the README or argument parsing update to handle a `-`. e.g. 

`-o "\-7"` works

`-o -7`
`-o "-7"` generate "No GMT time offset provided" error

This was noticed in GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

**Comment by khufkens** [comment]
Fixed in [README ](https://github.com/bluegreen-labs/phenocam_installation_tool_v2/commit/241ffe45a32454d84e72ae04a2158d466e6c0b81)
